-- CREATE TABLE emp (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   name VARCHAR(30) NOT NULL,
--   employee_id VARCHAR(20) NOT NULL,
--   department VARCHAR(50) NOT NULL,
--   dob DATE NOT NULL,
--   gender ENUM('Male', 'Female') NOT NULL,
--   designation VARCHAR(50) NOT NULL,
--   salary DECIMAL(10, 2) NOT NULL
-- );